---
title: "Data Import"
output: guthub_document
---

```{r}
library(tidyverse)
library(readxl)
library(haven)
```

let's import a dataset.

```{r}
litters_df = 
  read_csv( "data_import_examples/FAS_litters.csv")
```

look a r your data!

```{r}
names(litters_df)
```

```{r}
litters_df
```

sometimes skimming data is neat?
```{r}
skimr::skim(litters_df)
```

##fix the missingness
```{r}
litters_df =
  read_csv("data_import_examples/FAS_litters.csv", na = c("NA",".",""))
```

```{r}
litters_df = janitor::clean_names(litters_df)
names(litters_df)
```

##import dataset
```{r}
pups_df = 
  read_csv(
    "data_import_examples/FAS_litters.csv",
    skip =3,
    na = c("NA",".","")
    )

pupu_df = 
  janitor::clean_names(pups_df)
```



## key what about excel
CSVs are really great but sometimes you get an excel files
```{r}
mlb_df = 
  read_excel("data_import_examples/mlb11.xlsx")
```


```{r}
fotr_dt =
  read_excel("data_import_examples/mlb11.xlsx", range = "B3:D6")
```

## SAS????
```{r}
pulse_df =
  read_sas("data_import_examples/public_pulse_data.sas7bdat")
  
pulse_df = 
  janitor::clean_names(pulse_df)
```


## why do I hate .csv?
```{r}
litters_df_base = 
  read_csv("data_import_examples/FAS_litters.csv")
```
